### ISSUE TITLE
Support Cluster-Wide Operator

### ISSUE THREAD

**Issue by buckhx** [nats-io/nats-operator#103]
Would love for the nats-operator to function in a similar way to istio where there is a management namespace and the operator can watch all namespaces (w/ opt-out). Our main use can for this is we leverage namespaces at the environment level.

My ideal setup with where resources are defined would be as follows:

__Cluster__
* ClusterRole
* CRDs

__ns: nats-system__
* ServiceAccount
* Deployment
* ClusterRoleBinding

__ns: dev__
* NatsCluster (size: 1)

__ns: staging__
* NatsCluster (size: 3)

__ns: production__
* NatsCluster (size: 3)

**Comment by pires** [comment]
This is something we've discussed and have code for (not merged), however we have other features we want to add before looking into this.
