### ISSUE TITLE
How to set tls timeout ?

### ISSUE THREAD

**Issue by nithinkd-geon** [nats-io/nats-operator#153]
Hello

How to set tls timeout in tls section?

**Comment by wallyqs** [comment]
Looks like can't right now since the option is missing here... https://github.com/nats-io/nats-operator/blob/b93df8992303ed4a8f33c9994f306f5784e9fbb6/pkg/util/kubernetes/kubernetes.go#L157-L169

**Comment by wallyqs** [comment]
We should add an option here to be able to set it: https://github.com/nats-io/nats-operator/blob/master/pkg/apis/nats/v1alpha2/cluster.go#L156-L168

**Comment by nithinkd-geon** [comment]
@wallyqs  what should be the default timeout value?

**Comment by wallyqs** [comment]
@nithinkd-geon the default is 0.5 secs: https://github.com/nats-io/gnatsd/blob/master/server/const.go#L76-L77

**Comment by nithinkd-geon** [comment]
@wallyqs  thanks
