### ISSUE TITLE
Add support for `clientAuthFile`

### ISSUE THREAD

**Issue by schancel** [nats-io/nats-operator#156]
Add a `auth` config item `clientAuthFile` which tells nats operator to adjust the location of the nats auth configuration file.  The purpose of this would be for cases where secrets are coming from an `initContainer` defined in the `NatsCluster` definition.

**Comment by schancel** [comment]
You can assign this to me, I'm going to submit a pull request.

**Comment by wallyqs** [comment]
Fixed via #159
