### ISSUE TITLE
Revamp upgrade

### ISSUE THREAD

**Issue by pires** [nats-io/nats-operator#16]
Need to find a way to upgrade live clusters with minimum disruption, e.g. no message loss.

**Comment by pires** [comment]
@brunomcustodio you were supposed to create this ticket and add the info we discuss.

**Comment by brunomcustodio** [comment]
@pires I was waiting for `rework` to be merged in order to do that 😇 Also, I now need some input about pires/kubernetes-nats-cluster#9.

I will fully describe the problem once I can get my hands on my notebook (and also run some more tests).

**Comment by pires** [comment]
Ping me when the issue in the other repo is done.

**Comment by igorvpcleao** [comment]
Hi @bmcstdio  and @pires,

Is it safe to upgrade a nats-operator image nowadays?
I've just forked this repo and modified it a little bit to add a second container running nats-exporter for Prometheus.

Now I need to update the operator image, but I'm not sure about data consistency during the process.
Can I update its image and delete every nats pod, one by one, until cluster get fully synced again?

**Comment by wallyqs** [comment]
Currently only NATS server is supported and it is stateless, so there would be a few disconnects during the process but in general apps using NATS would have retry logic anyway so it should be safe to upgrade as clients would eventually reconnect to a node in the cluster.

**Comment by pires** [comment]
There's no guarantee messages will not get lost, though.

**Comment by igorvpcleao** [comment]
Thx @wallyqs and @pires!
Are you guys interested in adding a prometheus-exporter container within nats-pod managed by the operator?
I forked this repo to add this feature, but perhaps it may be useful for more people. I don't know.

**Comment by wallyqs** [comment]
@igorvpcleao that sounds great, feel free to submit the PR and will take a look 👍

**Comment by pires** [comment]
Fixed by #105.
