### ISSUE TITLE
2.0.0 Does not work with Nats Operator

### ISSUE THREAD

**Issue by charles-d-burton** [nats-io/nats-operator#194]
- [x] Defect

 
## Defects 
You'll then see the following in the logs:

Events:
  Type     Reason     Age   From                 Message
  ----     ------     ----  ----                 -------
  Normal   Scheduled  88s   default-scheduler    Successfully assigned default/nats-cluster-1 to kube-node3
  Normal   Pulling    87s   kubelet, kube-node3  Pulling image "nats:2.0.0"
  Normal   Pulled     84s   kubelet, kube-node3  Successfully pulled image "nats:2.0.0"
  Normal   Created    84s   kubelet, kube-node3  Created container nats
  Warning  Failed     83s   kubelet, kube-node3  Error: failed to create containerd task: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/gnatsd\": stat /gnatsd: no such file or directory": unknown
#### Versions of `gnatsd` and affected client libraries used:
2.0.0
#### OS/Container environment:
Kubernetes 1.14
#### Steps or code to reproduce the issue:
 Ensure that you have a working version of the nats operator installed in a Kubernetes cluster
kubectl apply the following file
`apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: nats-cluster
spec:
  size: 3
  version: "2.0.0"
#### Expected result:
 A running NATS Cluster
#### Actual result:
 A not running NATS Cluster

**Comment by wallyqs** [comment]
Right because there is no symlink for `gnatsd` in the `FROM scratch` image...  Need to update the operator for this, but you can use this image instead which we also maintain:

```
serverImage: "synadia/nats-server"
version: "2.0.0"
```

**Comment by charles-d-burton** [comment]
Heh, I think it would work but currently there's no ARM build.

**Comment by wallyqs** [comment]
I will take a look at pushing a version of the operator where this is fixed tomorrow.  If you want to try to create your own arm image for now, this is the Dockerfile that can be used to generate an 2.0.0 compatible image: https://github.com/nats-io/nats-server/blob/master/docker/Dockerfile.alpine

**Comment by charles-d-burton** [comment]
Thanks, I'll for sure take a look at it.  Does the build system support cross-compilation?  I could tackle getting this and the streaming operator working with ARM by emulating how the nats-server build and docker generation happens.

**Comment by wallyqs** [comment]
hey @charles-d-burton, the dockerfile I shared does not support cross compilation, but also I am about to merge https://github.com/nats-io/nats-operator/pull/195 and then push the image of the operator this morning that would support 2.0.0 image.  I pushed my own image here for now `wallyqs/nats-operator:0.6.0` but think won't work on ARM as is right now, contributions on getting the operator running on ARM very welcome too 👍

**Comment by wallyqs** [comment]
Fixed via  #195
