### ISSUE TITLE
Helm install error - pod nats-operator can't start

### ISSUE THREAD

**Issue by SergeSpinoza** [nats-io/nats-operator#211]
When I install NATS via helm - pod nats-operator can't start. Pod error is: 
```
time="2019-09-19T13:23:14Z" level=info msg="nats-operator Version: 0.4.4-v1alpha2+git"
time="2019-09-19T13:23:14Z" level=info msg="Git SHA: bbff797"
time="2019-09-19T13:23:14Z" level=info msg="Go Version: go1.11.2"
time="2019-09-19T13:23:14Z" level=info msg="Go OS/Arch: linux/amd64"
time="2019-09-19T13:23:14Z" level=fatal msg="failed to list pods in the \"nats-io\" namespace: pods is forbidden: User \"system:serviceaccount:default:nats-operator\" cannot list resource \"pods\" in API group \"\" in the namespace \"nats-io\""
```

**Install command**
```
helm install --name my-release .
```

**values.yaml**
cluster.version: 2.0.4
Other all parameters in `values.yaml` is default. 

**Setup**
- Kubernetes v1.15.3 (Bare metal)
- NATS Operator v0.4.4
- NATS Server v2.0.4

**Comment by VanilaBear** [comment]
kubectl create namespace nats-io

**Comment by SergeSpinoza** [comment]
> kubectl create namespace nats-io

This namespace is allready exists. This is the first thing I did.

**Comment by hatung** [comment]
helm install --name my-release --namespace=nats-io .

**Comment by Inkdpixels** [comment]
@SergeSpinoza This is due to the fact that the helm chart currently does not make use of the standardized `{{ .Release. Namespace }}` value in the deployment of the operator. 

I am looking to submit a PR this evening to fix this.

**Comment by devKlausS** [comment]
can reproduce the issue

```

time="2019-11-07T08:28:54Z" level=info msg="nats-operator Version: 0.4.4-v1alpha2+git"
time="2019-11-07T08:28:54Z" level=info msg="Git SHA: bbff797"
time="2019-11-07T08:28:54Z" level=info msg="Go Version: go1.11.2"
time="2019-11-07T08:28:54Z" level=info msg="Go OS/Arch: linux/amd64"
time="2019-11-07T08:28:54Z" level=fatal msg="failed to list pods in the \"nats-io\" namespace: pods is forbidden: User \"system:serviceaccount:default:nats-operator\" cannot list resource \"pods\" in API group \"\" in the namespace \"nats-io\""
```

**Comment by devKlausS** [comment]
> helm install --name my-release --namespace=nats-io .

what if I want to install nats in a different namespace. It looks like `nats-io` is hardcoded

**Comment by devKlausS** [comment]
@SergeSpinoza this solves the problem https://github.com/devKlausS/nats-operator/commit/67401fbaa0016a5c3e8c6c987785e9803e56387d

**Comment by SergeSpinoza** [comment]
@devKlausS thanks!
