### ISSUE TITLE
Pods not restarting following config changes

### ISSUE THREAD

**Issue by AmandaHassoun** [nats-io/nats-operator#235]
I've set the `enableConfigReload` flag to true assuming every time I make changes to the CRD (e.g. set debug to true or increase the MaxPayload), the pods would be restarted in order to pick up these changes but this is not the case.. Am I missing something?

**Comment by chiaolun** [comment]
I believe it triggers a config reload by using `SIGHUP` not by restarting.
https://github.com/nats-io/nats-server/blob/6d5ac0a5e3944a4744c5da27e9c2322fcbb0c8b5/server/signal.go#L59

**Comment by AmandaHassoun** [comment]
Nice! thanks for digging into this @chiaolun 👍
