### ISSUE TITLE
Signal NATS to reload configuration (TLS)

### ISSUE THREAD

**Issue by jackieluc** [nats-io/nats-operator#239]
I am running nats-operator with TLS verify and wish to reload the configuration for the NATS clusters when the TLS certificates get renewed so that new certificates are used. What is the best way to achieve this? I've enabled configuration reload but can't seem to quite understand or find out how to trigger it. 

Is there a way to signal a reload like in [nats-server](https://docs.nats.io/nats-server/nats_admin/signals)?

**Comment by atpons** [comment]
I have created a pull request to fix this: https://github.com/nats-io/nats-operator/pull/281
