### ISSUE TITLE
Create nats leaf remote connection

### ISSUE THREAD

**Issue by Kampe** [nats-io/nats-operator#280]
Hello!

Is there any documentation for how to create the remote connection to a leaf node? 

In my supercluster, I'm creating the cluster with 
```
apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  labels:
    app: global-nats
  name: global-nats-cluster
spec:
  natsConfig:
    writeDeadline: 5s
    debug: true
    trace: true
  pod:
    enableConfigReload: true
    enableMetrics: true
    metricsImage: synadia/prometheus-nats-exporter
    metricsImageTag: 0.5.0
    reloaderImage: connecteverything/nats-server-config-reloader
    reloaderImagePullPolicy: IfNotPresent
    reloaderImageTag: 0.6.0
  size: 2
  version: 2.1.2
  leafnodeConfig:
    hostPort: 4224
```

I assume there's a way to specify the remote leaf connections in a similar way?

**Comment by wallyqs** [comment]
Hi @Kampe sorry for the inconvenience, leafnode remotes are not exposed in the config yet in the operator... https://github.com/nats-io/nats-operator/issues/268

**Comment by Kampe** [comment]
Hooray! Thanks all!
