### ISSUE TITLE
Add support for arm64 Docker images

### ISSUE THREAD

**Issue by tegk** [nats-io/nats-operator#296]
Kindly requesting to support arm64 builds :-)

**Comment by alexellis** [comment]
Happy to point you at some of our multi-arch examples if you need a hand with this. We are currently moving from the Docker Hub + Travis to GHCR + GitHub Actions with buildx

**Comment by wallyqs** [comment]
Thanks @alexellis that would help a lot!

**Comment by alexellis** [comment]
I suggest starting here https://github.com/openfaas/faas-netes/commit/bf7fb6d2b6ed01cc308b0dd5e79bb2bb6ced8d24

**Comment by variadico** [comment]
All right. Looks like this is good to go.
@tegk, can you verify the arm64 images work on your end?

https://hub.docker.com/r/connecteverything/nats-operator/tags
