### ISSUE TITLE
HostPort when enableClientsHostPort is set to false

### ISSUE THREAD

**Issue by mtryfoss** [nats-io/nats-operator#300]
Hi,

I see that gateway, leaf or websocket config automatically enables listening on a HostPort. In my setup, we use Calico CNI where all Pods do have direct connectivity to our environment. I use discovery through a service with "externalTrafficPolicy: Local" which seems to work perfectly.

	if gatewayPort > 0 {
		port := v1.ContainerPort{
			Name:          "gateway",
			ContainerPort: int32(gatewayPort),
			Protocol:      v1.ProtocolTCP,
			HostPort:      int32(gatewayPort),
		}
		ports = append(ports, port)
	}
	if leafnodePort > 0 {
		port := v1.ContainerPort{
			Name:          "leaf",
			ContainerPort: int32(leafnodePort),
			Protocol:      v1.ProtocolTCP,
			HostPort:      int32(leafnodePort),
		}
		ports = append(ports, port)
	}
	if websocketPort > 0 {
		port := v1.ContainerPort{
			Name:          "websocket",
			ContainerPort: int32(websocketPort),
			Protocol:      v1.ProtocolTCP,
			HostPort:      int32(websocketPort),
		}
		ports = append(ports, port)
	}

Would you accept a PR making it possible to disable this behaviour (enabled by default), making it only request a ContainerPort? 
For example: 

disableGatewaysHostPort
disableLeafnodesHostPort
disableWebsocketsHostPort

**Comment by wallyqs** [comment]
Sounds like a good change to me, we'd gladly accept a PR like that.

**Comment by mtryfoss** [comment]
Updated the PR with new master branch now. Hope it looks ok.
