### ISSUE TITLE
'the NATS Operator is not recommended to be used for new deployments.'

### ISSUE THREAD

**Issue by jmell-slg** [nats-io/nats-operator#337]
Is this project going to be EOL?

**Comment by wallyqs** [comment]
Yes please try with the Helm Charts:

https://github.com/nats-io/k8s/tree/main/helm/charts/nats

Or for managing Streams with JetStream:

https://github.com/nats-io/nack

**Comment by jmell-slg** [comment]
Thank you for the very quick response. Would ask questions again A+++++++++++++++++++
