### ISSUE TITLE
prometheus support in nats-operator

### ISSUE THREAD

**Issue by RyanGordon** [nats-io/nats-operator#40]
When https://github.com/nats-io/prometheus-nats-exporter/issues/48 is completed, it would be great if the option to add prometheus exporter was added to nats-operator.

**Comment by wallyqs** [comment]
Yep agree, will take a look at adding support

**Comment by wallyqs** [comment]
That's right, so I think that the exporter container PodSpec would be running as part of the same PodSpec of the deployed NATS servers. (1 Pod = exporter + nats server)

**Comment by entone** [comment]
Any update on this? 

I've added prometheus-nats-exporter, and pointed it at the headless mgmt service created by the operator. It appears to find all the pods in the cluster, but does not enumerate the pods, also some variables don't seem to be aggregated correctly.
