### ISSUE TITLE
Failed to re-create cluster

### ISSUE THREAD

**Issue by wzhliang** [nats-io/nats-operator#41]
I created a sample cluster with 

    kc apply -f example-nats-cluster.yaml -n nats-io

After playing with the cluster a while, I did 

    kc delete -f example-nats-cluster.yaml -n nats-io

and then

    kc apply -f example-nats-cluster.yaml -n nats-io

 again. But it failed this time, `describe` shows the following reason: 

    cluster create: fail to create shared config map: configmaps "example-nats-1" already exists

**Comment by wallyqs** [comment]
Thanks for the bug report, I will take a look at preventing this issue. Do you have some of the logs around from the nats-operator by any chance? (`kubectl logs nats-operator`)

As a workaround deleting the configmap would allow recreating using the same name:

```sh
kubectl delete cm example-nats-1
```

**Comment by wzhliang** [comment]
> time="2018-04-11T01:24:22Z" level=info msg="cluster is deleted by the user" cluster-name=example-nats-1 pkg=cluster
> time="2018-04-11T01:24:22Z" level=warning msg="retry report status in 5s: fail to update: failed to update CR status: the server reported a conflict" cluster-name=example-nats-1 pkg=cluster
> time="2018-04-11T01:24:27Z" level=info msg="deleting the failed cluster" cluster-name=example-nats-1 pkg=cluster
> time="2018-04-11T01:24:28Z" level=info msg="deleted pod (nats-8sbrf5hv5c)" pkg=gc
> time="2018-04-11T01:24:28Z" level=info msg="deleted pod (nats-nrlv8qm61h)" pkg=gc
> time="2018-04-11T01:24:28Z" level=info msg="deleted pod (nats-z91v1tx642)" pkg=gc
> time="2018-04-11T01:24:28Z" level=info msg="deleted service (example-nats-1)" pkg=gc
> time="2018-04-11T01:24:28Z" level=info msg="deleted service (example-nats-1-mgmt)" pkg=gc
> time="2018-04-11T01:25:25Z" level=info msg="apiserver closed watch stream, retrying after 5s..." pkg=controller
> time="2018-04-11T01:25:30Z" level=info msg="start watching at 6562255" pkg=controller
> time="2018-04-11T01:25:30Z" level=warning msg="fail to handle event: unsafe state. cluster (example-nats-1) was never created but we received event (DELETED)" pkg=controller
