### ISSUE TITLE
When is the next planned release?

### ISSUE THREAD

**Issue by marmotini** [nats-io/nats-operator#46]

**Comment by wallyqs** [comment]
I think probably early next week

**Comment by marmotini** [comment]
Thank you!

**Comment by wallyqs** [comment]
Quick update, there are a couple of PRs that want to include in the release so next week looking more likely

**Comment by marmotini** [comment]
Thank you for the update.

**Comment by wallyqs** [comment]
New release is up: https://github.com/nats-io/nats-operator/releases/tag/v0.2.2
