### ISSUE TITLE
No clusters created after CRD creation. RBAC enabled.

### ISSUE THREAD

**Issue by pigmej** [nats-io/nats-operator#66]
Hey,

I'm using local cluster based on https://github.com/Mirantis/kubeadm-dind-cluster in 1.11 version with 3 nodes:
```
NAME          STATUS    ROLES     AGE       VERSION  
kube-master   Ready     master    30m       v1.11.0
kube-node-1   Ready     <none>    29m       v1.11.0
kube-node-2   Ready     <none>    29m       v1.11.0
kube-node-3   Ready     <none>    29m       v1.11.0
```
RBAC is enabled so therefore I executed:
`kubectl apply -f https://raw.githubusercontent.com/nats-io/nats-operator/master/example/deployment-rbac.yaml`
which ended up with:
```
$ kubectl -n nats-io logs deployment/nats-operator
time="2018-08-24T11:20:15Z" level=info msg="nats-operator Version: 0.2.3-v1alpha2+git"
time="2018-08-24T11:20:15Z" level=info msg="Git SHA: d88048a"
time="2018-08-24T11:20:15Z" level=info msg="Go Version: go1.9"
time="2018-08-24T11:20:15Z" level=info msg="Go OS/Arch: linux/amd64"
time="2018-08-24T11:20:33Z" level=info msg="Event(v1.ObjectReference{Kind:\"Endpoints\", Namespace:\"nats-io\", Name:\"nats-operator\", UID:\"fd436814-a78d-11e8-9920-e20744c33dad\", APIVersion:\"v1\", ResourceVersion:\"3701\", FieldPath:\"\"}): type: 'Normal' reason: 'LeaderElection' nats-operator-f44c5854d-ph6cg became leader"
time="2018-08-24T11:20:33Z" level=info msg="finding existing clusters..." pkg=controller
time="2018-08-24T11:20:33Z" level=info msg="starts running from watch version: 3702" pkg=controller
time="2018-08-24T11:20:33Z" level=info msg="start watching at 3702" pkg=controller
time="2018-08-24T11:22:16Z" level=info msg="apiserver closed watch stream, retrying after 5s..." pkg=controller
time="2018-08-24T11:22:21Z" level=info msg="start watching at 3702" pkg=controller
time="2018-08-24T11:23:52Z" level=info msg="apiserver closed watch stream, retrying after 5s..." pkg=controller
time="2018-08-24T11:23:57Z" level=info msg="start watching at 3702" pkg=controller
```
so far so good BUT then
```
$ kubectl apply -f https://raw.githubusercontent.com/nats-io/nats-operator/master/example/example-nats-cluster.yaml
natscluster.nats.io/example-nats-1 created```
and then:
```$ kubectl get natsclusters.nats.io
NAME             AGE                                                         
example-nats-1   2s
```

but sadly
```
$ kubectl -n nats-io get pods -l nats_cluster=example-nats-1
No resources found.
```
There are no logs in operator no other pods what so ever. I tried to check what it actually tries to do but it just seems that it's stalled. I also recreated deployment and the same.

**Comment by wallyqs** [comment]
Thanks for the report, could you also shared `describe` on the `nats-operator` pod? I will try to reproduce on a dind environment.

**Comment by geriBatai** [comment]
I had the same issue. [Cluster example CRD](https://raw.githubusercontent.com/nats-io/nats-operator/master/example/example-nats-cluster.yaml) is not namespaced, yet operator is looking for a namespaced objects. So, to fix your issue, run:

```
kubectl create -n nats-io -f https://raw.githubusercontent.com/nats-io/nats-operator/master/example/example-nats-cluster.yaml
```

I think only documentation should be fixed.

**Comment by prune998** [comment]
The issue here is that the Nats Operator only watch in its local namespace. I think this is the issue and the operator should watch at the cluster level. 

Any chance this can be done ?

**Comment by wallyqs** [comment]
Thanks for the feedback here everyone, I will separate the deployment manifest and the RBAC policy setup from being in the same manifest so that it can be customized, and also the `default` namespace for the operator which is more common instead.
