### ISSUE TITLE
TLS Route Certificates need IP SANs when Deployed to same IP

### ISSUE THREAD

**Issue by rclayton-the-terrible** [nats-io/nats-operator#73]
I know this is not a NATS issue, but I wanted to point out an issue we are experiencing due to the nature of k8s deployments and the way the operator is currently configured.

Also, I'm not sure if this is related to https://github.com/nats-io/nats-operator/issues/32

I'm using a wildcard CN `*.nats-mgmt.nats-io.svc` for the routes and when a cluster node is deployed with the same IP Address as another node, I receive the following error:

```
[1] 2018/10/12 18:46:42.988808 [ERR] 172.28.219.187:6222 - rid:4 - TLS route handshake error: x509: cannot validate certificate for 172.28.219.187 because it doesn't contain any IP SANs
```

I could add IP SANs to my certificate, but that seems crazy since the IP is unpredictable (and IP SANs can't use wildcards AFAIK).

Is there a strategy I'm missing?  Perhaps we need an option to skip hostname verification? Or better yet, force deployment to different IPs?

**Comment by wallyqs** [comment]
Fixed via #32
