### ISSUE TITLE
Readiness probe never passes when updating nats-operator deployment 

### ISSUE THREAD

**Issue by dijitali** [nats-io/nats-operator#77]
When making changes to `nats-operator` deployment, the pod in the new replicaset from updated deployment never passes readiness probe until previous `nats-operator` pod is manually deleted.

### Example
For example, I apply the updated deployment (with a newer nats-operator image version):
```
kubectl apply -f ./nats-operator/ --namespace my-namespace
```

I observe a new pod is created:
```
kubectl get pods -l app=nats-operator --namespace=my-namespace
NAME                             READY   STATUS    RESTARTS   AGE
nats-operator-68856b7bb6-tlghf     1/1     Running   0          4h17m
nats-operator-68856b7bb6-ntpwj     0/1     Running   0          15m
```

But the pod is failing the readiness probe:
```
kubectl describe pod nats-operator-68856b7bb6-ntpwj --namespace=my-namespace

Name:           nats-operator-68856b7bb6-ntpwj
Namespace:      my-namespace
…
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
…
Warning  Unhealthy              3m29s (x149 over 28m)  kubelet, gke-my-cluster-default-pool-xxx  Readiness probe failed: HTTP probe failed with statuscode: 500
```

If I delete the old pod:
```
kubectl delete pod nats-operator-5fc7849b6-tlghf --namespace=my-namespace
```

The new one becomes Ready:
```
kubectl get pods -l app=nats-operator --namespace=my-namespace
NAME                             READY   STATUS    RESTARTS   AGE
nats-operator-68856b7bb6-ntpwj   1/1     Running   0          33m
```

### Potential Solution
Change `nats-operator` deployment to use Recreate strategy (default is a Rolling Update) so the old pod is deleted first:
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy

But this would mean `nats-operator` might not exist for a short period, is that actually a problem?  The NATS cluster should still be in place and functional during that time.

**Comment by wallyqs** [comment]
There wouldn't be an issue if the operator is temporarily down since this will not affect the running clusters, so think we could adopt recreate strategy in this case.

**Comment by pires** [comment]
I think a more robust solution would be for the readiness probe to pass, by having the operator ignore whether it's the leader or not, when computing readiness. I'll be working over the coming days.

**Comment by pires** [comment]
Thanks for reporting, @dijitali!
