### ISSUE TITLE
error viewing pod in gui

### ISSUE THREAD

**Issue by lunne** [nats-io/nats-operator#78]
Everything works just fine but if i try to look at a pod from the gui i get this:
![image](https://user-images.githubusercontent.com/7102889/47349647-526afa00-d6b4-11e8-81d5-a46f84fc8106.png)

RBAC is enabled and i´ve installed the rbac-yaml.

**Comment by pires** [comment]
This operator doesn't provide a GUI, atm. Therefore, please report to the authors of the GUI you're using.
