### ISSUE TITLE
Missing client authentication enabled check in natscluster.yaml helm template

### ISSUE THREAD

**Issue by rakeshv1** [nats-io/nats-operator#86]
Currently the auth section in natscluster.yaml does not check if client authentication is set to enabled in values.yaml. 

It is missing `{{- if .Values.auth.enabled }}`

```
  {{- if .Values.auth.enabled }}
  auth:
    enableServiceAccounts: {{ .Values.auth.enableServiceAccounts }}
    clientsAuthSecret: {{ template "nats.fullname" . }}-clients-auth
    clientsAuthTimeout: 5
  {{- end }}
```

**Comment by pires** [comment]
@wallyqs can you please validate this? I have no experience with Helm.

**Comment by gilliangoud** [comment]
Ran into this issue aswell, came to the same conslusion as the fix above. Please add it in the chart :)

**Comment by pires** [comment]
Can any of you please open a PR so that @wallyqs can review? Thanks!

**Comment by rakeshv1** [comment]
Created PR #149
