### ISSUE TITLE
How to update server config?

### ISSUE THREAD

**Issue by OtaK** [nats-io/nats-operator#87]
Hello,

I've been trying to figure out how to set a custom configuration for the NATS Cluster, and I couldn't find anything in the docs or looking for uses of `ServerConfig` in the code.

Any leads or clues on how to set it?
My specific need is to find out how to increase max_payload_size.

Thanks!

**Comment by wallyqs** [comment]
Not supported yet but most of the pieces to do it is there, needs to be added to be part of the NatsCluster spec: https://github.com/nats-io/nats-operator/blob/7f14a459720537f72e85495fd78803a7f28589b8/pkg/spec/cluster.go#L62

**Comment by OtaK** [comment]
Okay, what do you think of this implementation @wallyqs?
I'm having trouble setting up the dev environment, since there's not much documentation on contributing 😢 

https://github.com/nats-io/nats-operator/compare/master...YellowInnovation:feature/server-config

**Comment by pires** [comment]
I think I like your implementation but this requires validation from the NATS experts.

@wallyqs I think this adds up to #32 and #33. WDYT?

**Comment by wallyqs** [comment]
Fixed in master via #134

**Comment by nicklasfrahm** [comment]
@wallyqs Could we keep this open until this is actually released as an update to the Docker image?

**Comment by wallyqs** [comment]
@nicklasfrahm ok! reopening until next release is done, if you want to try this functionality already feel free to use this image too: `wallyqs/nats-operator:0.4.3-v1alpha2`

**Comment by wallyqs** [comment]
https://github.com/nats-io/nats-operator/releases/tag/v0.4.3
